### ISSUE TITLE
Is this framework support to port to android using JavaFX?

### ISSUE THREAD

**Issue by ebysofyan** [Kairos-Project/kairos-example#1]
Hello marconi.
I have an error when run task androidRelease.

error:
Caused by: org.gradle.api.GradleException: Exception in thread "main" com.android.dx.cf.iface.ParseException: InvokeDynamic not supported
    at com.android.dx.cf.cst.ConstantPoolParser.determineOffsets(ConstantPoolParser.java:226)
    at com.android.dx.cf.cst.ConstantPoolParser.parse(ConstantPoolParser.java:132)
    at com.android.dx.cf.cst.ConstantPoolParser.parseIfNecessary(ConstantPoolParser.java:124)
    at com.android.dx.cf.cst.ConstantPoolParser.getPool(ConstantPoolParser.java:115)
    at com.android.dx.cf.direct.DirectClassFile.parse0(DirectClassFile.java:482)
    at com.android.dx.cf.direct.DirectClassFile.parse(DirectClassFile.java:406)
    at com.android.dx.cf.direct.DirectClassFile.parseToEndIfNecessary(DirectClassFile.java:397)
    at com.android.dx.cf.direct.DirectClassFile.getAttributes(DirectClassFile.java:311)
    at com.android.multidex.MainDexListBuilder.hasRuntimeVisibleAnnotation(MainDexListBuilder.java:191)
    at com.android.multidex.MainDexListBuilder.keepAnnotated(MainDexListBuilder.java:167)
    at com.android.multidex.MainDexListBuilder.<init>(MainDexListBuilder.java:121)
    at com.android.multidex.MainDexListBuilder.main(MainDexListBuilder.java:91)
    at com.android.multidex.ClassReferenceListBuilder.main(ClassReferenceListBuilder.java:58)
**...while preparsing cst 0002 at offset 0000000f
...while parsing org/kairos/ActionBarDrawerToggle.class**

Execution failed for task ':createMainDexList'.

do you have a solution?
Thanks for sharing and good job for your kairos-framework.
Very Nice JavaFX UI Framework

**Comment by marconi1992** [comment]
No, kairos uses only the concept of Android to ease the javafx software development. but you may be interested in http://gluonhq.com/

**Comment by ebysofyan** [comment]
Oke thanks man
